### ISSUE TITLE
Unable to provide logs

### ISSUE THREAD

**Issue by Ibotmealot** [MMPlugins/LogSearch#1]
The plugin seems to find that there's logs containing the search inquery, however, is unable to actually give the logs. Instead it just says null. 

![image](https://user-images.githubusercontent.com/42391199/151640469-7b8614fa-9148-467c-ae12-e378f005f929.png)

**Comment by DarkView** [comment]
This plugin does not function properly with attachments.
Commit cc0c94fe9834fb2f04c043c05e97edb0727e3732 fixes this somewhat by displaying Thread numbers in all cases.
Please read [this (new) section](https://github.com/MMPlugins/LogSearch#attention) of the README which explains the issue and what do to if you do not use loglinks.
